[package]
name = "rust-lzo"
version = "0.1.0"
authors = ["Jeff Muizelaar <jmuizelaar@mozilla.com>"]
description = "A pure rust implementation of lzo converted from Linux's C implementation using corrode"
license = "GPL-2.0"

[dependencies]
libc = "0.2.21"
